### ISSUE TITLE
Can't copy URL from box

### ISSUE THREAD

**Issue by SWannell** [britishredcrosssociety/tracked-link-builder#31]
User reports:

> - It can be difficult to copy the generated URL.
> - Can't right-click to copy, highlighting doesn't work
> - Try to Ctrl+C but doesn't copy)

To investigate, do user testing to identify issues.

**Comment by SWannell** [comment]
Need front-end dev help

**Comment by raphaelleRC** [comment]
I changed the "readonly" property in the textarea to "disabled". They still won't be able to edit the content but should be able to select whatever they want now

**Comment by SWannell** [comment]
Heather Scott re-raised the "can't copy a URL issue":

> - I can't copy things from the link builder anymore for some strange reason
> - I've tried in a different browser

**Comment by SWannell** [comment]
This came up with Tina when I was there, so allowed me to check -- on her device, it was an IE/Edge issue, and the copying actually did work, it was just that the cursor changed to make it look like it wouldn't.
