### ISSUE TITLE
Added query + anchor combo bug

### ISSUE THREAD

**Issue by SWannell** [britishredcrosssociety/tracked-link-builder#49]
### Observed:

IF a user inputs a link that has both a custom query string AND an anchor fragment
THEN the resulting link is incorrect (merging the custom query string and anchor fragment into one non-functional query string parameter with the value "[customqueryparam]=[customqueryvalue][anchor]"

### Expected:

A user should be able to add a link that has both a custom query string and an anchor link.

### Example user selections

Medium | BRC work area | URL | Donate? | Source | Link type | Source code | Link location | CTA | Target / Audience
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Audio | General Fund Appeal | https://donate.redcross.org.uk/appeal/general-fund-appeal?spm=Regular%20Giving#appeal-intro | TRUE | Spotify | Donate Landing | 246802 | Interest | CTA | Non-science nerds

Gives the following: https://donate.redcross.org.uk/appeal/general-fund-appeal?spm=Regular+Givingappeal-intro&utm_campaign=General%20Fund%20Appeal&utm_source=Spotify&utm_medium=Audio&utm_content=Donate%20Landing_CTA&utm_term=246802_Interest_Non-science%20nerds&c_name=General%20Fund%20Appeal&c_source=Spotify&c_medium=Audio&c_creative=Donate%20Landing_CTA&c_code=246802&adg=Interest_Non-science%20nerds

**Comment by SWannell** [comment]
FYI @JulioPeral -- the work passed all the standard QA checks, so I integrated the branch. But I did notice one bug, niche enough that it didn't block me pushing this to live -- but would be great to get a fix for this too? ❤️

**Comment by SWannell** [comment]
(also noticed that there's a trailing ampersand with the anchor path, but given that doesn't actually cause a problem, I didn't raise a bug for that)

**Comment by JulioPeral** [comment]
Hey @SWannell, thanks a lot for testing and giving your feedback!

So, about that trailing ampersand, I actually added it just to be on the safe side and not mess up your tracking from the last query. But if it's not necessary, I can totally remove it. Happy for me to do it?

Now, let's talk about that standing issue you mentioned. I've got a fix for it! So, when a user inputs a link with an anchor at the end like "#appeal-intro", it wasn't being passed correctly to the newly built link. 
But here's the thing: if the user's URL input has multiple anchors, only the last one will be used. The anchor won't work unless it is at the end of the URL anyway. In the case of multiple anchors, are you happy with me using the last anchor and removing the other/s? 
So using this link: https://donate.redcross.org.uk/appeal/general-fund-appeal#Test?spm=Regular%20Giving#appeal-intro
would be like if the URL didn't have the #Test https://donate.redcross.org.uk/appeal/general-fund-appeal?spm=Regular%20Giving#appeal-intro
and "#appeal-intro" would be added at the end of the newly built link. 

Once again, thanks for bringing these things up. I'll make the necessary adjustments based on your feedback.

**Comment by SWannell** [comment]
I don't have confidence about whether to keep or remove the trailing ampersand! If you added it in on purpose, and you think there's a good reason for it, then happy to leave it in 😄 

On the core issue: I agree that we don't _need_† a use case for if people submit an 'incorrect' link

† I guess, if we wanted to, we could put an error warning next to the URL box? But that feels like a separate thing entirely, that could have more thought around it (i.e. add an alert if they put a tracked link itself in, saying we've removed the tracking; add an alert if the anchor isn't at the end, saying it should be; add an alert if people submit a link with two anchors flagging that they need to be at the end to work, + we'll only use the second one)

I'm curious though -- the bug I mentioned isn't about having two anchors in the link, but about having an anchor and a query string. Why did you mention the two anchors thing on this issue, are they related in some way?

**Comment by SWannell** [comment]
FYI @JulioPeral, I have partly addressed this in https://github.com/britishredcrosssociety/tracked-link-builder/pull/53:

* I read around, and confirmed that the trailing ampersand isn't best practice
* Also, the leading ampersand that it was added isn't best practice either => removed that too
* I _also_ addressed this issue's bug

It passed all the QA checks (which I also partly automated as part of that PR 😎)
